[package]
name = "advent"
version = "0.1.0"
edition = "2021"
default-run = "advent"

[dependencies]
anyhow = "1.0.66"
automod = "1.0.4"
emergence = "1.0.1"
nom = "7.1.1"
rand = "0.8.5"

[profile.release]
overflow-checks = true
