[package]
name = "advent"
version = "0.1.0"
edition = "2021"
default-run = "advent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
automod = "1.0.4"
emergence = "1.0.1"
nom = "7.1.1"
